name: Checkov

on:
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          framework: terraform
          # 1. Only fail the build for critical security flaws
          hard_fail_on: HIGH,CRITICAL 
    # 2. Alternatively, set to true to never block the pipeline at all
          soft_fail: false  